pipeline {
    agent {
        docker {
            args '-u root:root'
            image 'node:lts-buster-slim'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
    }
    stage('Docker Build') {
          agent any
          steps {
          sh 'docker build -t react=image:latest .'
        }
      }
}